services:
  puzzfinder:
    container_name: puzzfinder-api
    image: puzzfinder-api
    build: .
    ports:
      - "50000:50000"
    volumes:
      - ../puzzfinder-db:/app/db
    environment:
      - DB_PATH=/app/db/puzzfinder.db
    restart: unless-stopped
