services:
    puzzfinder:
        container_name: puzzfinder-api
        image: puzzfinder-api
        build: .
        env_file: .env
        ports:
            - "50000:50000"
        volumes:
            - ${PUZZLES_DB}:/app/puzzfinder.db
        restart: unless-stopped
