services:
  puzzfinder:
    container_name: puzzfinder-api
    image: puzzfinder-api
    build: .
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ../puzzfinder-db/puzzfinder.db:/app/puzzfinder.db
    restart: unless-stopped
