/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/puzzles/search": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Search puzzles by filters, sort order and pagination */
		post: operations["searchPuzzles"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/puzzles/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a single puzzle by its id */
		get: operations["getPuzzleById"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		NumberRange: {
			min?: number;
			max?: number;
			equals?: number;
		};
		/** @enum {string} */
		SortField: "rating" | "movesNumber" | "popularity" | "nbPlays" | "puzzleId";
		/** @enum {string} */
		PuzzleTheme:
			| "advancedPawn"
			| "advantage"
			| "anastasiaMate"
			| "arabianMate"
			| "attackingF2F7"
			| "attraction"
			| "backRankMate"
			| "balestraMate"
			| "blindSwineMate"
			| "bishopEndgame"
			| "bodenMate"
			| "castling"
			| "capturingDefender"
			| "cornerMate"
			| "crushing"
			| "discoveredCheck"
			| "doubleBishopMate"
			| "dovetailMate"
			| "equality"
			| "kingsideAttack"
			| "clearance"
			| "defensiveMove"
			| "deflection"
			| "discoveredAttack"
			| "doubleCheck"
			| "endgame"
			| "enPassant"
			| "epauletteMate"
			| "exposedKing"
			| "fork"
			| "hangingPiece"
			| "hookMate"
			| "interference"
			| "intermezzo"
			| "killBoxMate"
			| "pillsburysMate"
			| "morphysMate"
			| "swallowstailMate"
			| "triangleMate"
			| "vukovicMate"
			| "knightEndgame"
			| "long"
			| "master"
			| "masterVsMaster"
			| "mate"
			| "mateIn1"
			| "mateIn2"
			| "mateIn3"
			| "mateIn4"
			| "mateIn5"
			| "middlegame"
			| "oneMove"
			| "opening"
			| "operaMate"
			| "pawnEndgame"
			| "pin"
			| "promotion"
			| "queenEndgame"
			| "queenRookEndgame"
			| "queensideAttack"
			| "quietMove"
			| "rookEndgame"
			| "sacrifice"
			| "short"
			| "skewer"
			| "smotheredMate"
			| "superGM"
			| "trappedPiece"
			| "underPromotion"
			| "veryLong"
			| "xRayAttack"
			| "zugzwang";
		PuzzleFilters: {
			rating?: components["schemas"]["NumberRange"];
			movesNumber?: components["schemas"]["NumberRange"];
			popularity?: components["schemas"]["NumberRange"];
			nbPlays?: components["schemas"]["NumberRange"];
			themes?: components["schemas"]["PuzzleTheme"][];
		};
		PuzzleSearchOptions: {
			filters?: components["schemas"]["PuzzleFilters"];
			sort?: {
				field: components["schemas"]["SortField"];
				/** @enum {string} */
				order: "asc" | "desc";
			};
			pagination?: {
				/** @default 1 */
				page: number;
				/** @default 10 */
				limit: number;
			};
		};
		Puzzle: {
			puzzleId: string;
			fen: string;
			/** @description Solution moves in UCI notation, space-separated */
			moves: string;
			movesNumber: number;
			rating: number;
			ratingDeviation: number;
			popularity: number;
			nbPlays: number;
			gameUrl: string;
			openingTags?: string | null;
			themes: components["schemas"]["PuzzleTheme"][];
		};
		PaginatedPuzzles: {
			data: components["schemas"]["Puzzle"][];
			pagination: {
				page: number;
				limit: number;
				total: number;
				totalPages: number;
			};
		};
		Error: {
			error: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	searchPuzzles: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PuzzleSearchOptions"];
			};
		};
		responses: {
			/** @description Paginated list of matching puzzles */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PaginatedPuzzles"];
				};
			};
			/** @description Request body failed validation */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Error"];
				};
			};
		};
	};
	getPuzzleById: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The puzzle */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Puzzle"];
				};
			};
			/** @description No puzzle with this id */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Error"];
				};
			};
		};
	};
}
