CREATE TABLE puzzles (
    id TEXT PRIMARY KEY,
    fen TEXT NOT NULL,
    moves TEXT NOT NULL,
    movesNumber INTEGER NOT NULL,
    rating INTEGER NOT NULL,
    ratingDeviation INTEGER NOT NULL,
    popularity INTEGER NOT NULL,
    nbPlays INTEGER NOT NULL,
    gameUrl TEXT NOT NULL,
    openingTags TEXT,

    -- Jesus, forgive my wicked soul
    themeAdvancedPawn BOOLEAN NOT NULL CHECK (themeAdvancedPawn IN (0, 1)),
    themeAdvantage BOOLEAN NOT NULL CHECK (themeAdvantage IN (0, 1)),
    themeAnastasiaMate BOOLEAN NOT NULL CHECK (themeAnastasiaMate IN (0, 1)),
    themeArabianMate BOOLEAN NOT NULL CHECK (themeArabianMate IN (0, 1)),
    themeAttackingF2F7 BOOLEAN NOT NULL CHECK (themeAttackingF2F7 IN (0, 1)),
    themeAttraction BOOLEAN NOT NULL CHECK (themeAttraction IN (0, 1)),
    themeBackRankMate BOOLEAN NOT NULL CHECK (themeBackRankMate IN (0, 1)),
    themeBishopEndgame BOOLEAN NOT NULL CHECK (themeBishopEndgame IN (0, 1)),
    themeBodenMate BOOLEAN NOT NULL CHECK (themeBodenMate IN (0, 1)),
    themeCastling BOOLEAN NOT NULL CHECK (themeCastling IN (0, 1)),
    themeCapturingDefender BOOLEAN NOT NULL CHECK (themeCapturingDefender IN (0, 1)),
    themeCrushing BOOLEAN NOT NULL CHECK (themeCrushing IN (0, 1)),
    themeDoubleBishopMate BOOLEAN NOT NULL CHECK (themeDoubleBishopMate IN (0, 1)),
    themeDovetailMate BOOLEAN NOT NULL CHECK (themeDovetailMate IN (0, 1)),
    themeEquality BOOLEAN NOT NULL CHECK (themeEquality IN (0, 1)),
    themeKingsideAttack BOOLEAN NOT NULL CHECK (themeKingsideAttack IN (0, 1)),
    themeClearance BOOLEAN NOT NULL CHECK (themeClearance IN (0, 1)),
    themeDefensiveMove BOOLEAN NOT NULL CHECK (themeDefensiveMove IN (0, 1)),
    themeDeflection BOOLEAN NOT NULL CHECK (themeDeflection IN (0, 1)),
    themeDiscoveredAttack BOOLEAN NOT NULL CHECK (themeDiscoveredAttack IN (0, 1)),
    themeDoubleCheck BOOLEAN NOT NULL CHECK (themeDoubleCheck IN (0, 1)),
    themeEndgame BOOLEAN NOT NULL CHECK (themeEndgame IN (0, 1)),
    themeExposedKing BOOLEAN NOT NULL CHECK (themeExposedKing IN (0, 1)),
    themeFork BOOLEAN NOT NULL CHECK (themeFork IN (0, 1)),
    themeHangingPiece BOOLEAN NOT NULL CHECK (themeHangingPiece IN (0, 1)),
    themeHookMate BOOLEAN NOT NULL CHECK (themeHookMate IN (0, 1)),
    themeInterference BOOLEAN NOT NULL CHECK (themeInterference IN (0, 1)),
    themeIntermezzo BOOLEAN NOT NULL CHECK (themeIntermezzo IN (0, 1)),
    themeKillBoxMate BOOLEAN NOT NULL CHECK (themeKillBoxMate IN (0, 1)),
    themeVukovicMate BOOLEAN NOT NULL CHECK (themeVukovicMate IN (0, 1)),
    themeKnightEndgame BOOLEAN NOT NULL CHECK (themeKnightEndgame IN (0, 1)),
    themeLong BOOLEAN NOT NULL CHECK (themeLong IN (0, 1)),
    themeMaster BOOLEAN NOT NULL CHECK (themeMaster IN (0, 1)),
    themeMasterVsMaster BOOLEAN NOT NULL CHECK (themeMasterVsMaster IN (0, 1)),
    themeMate BOOLEAN NOT NULL CHECK (themeMate IN (0, 1)),
    themeMateIn1 BOOLEAN NOT NULL CHECK (themeMateIn1 IN (0, 1)),
    themeMateIn2 BOOLEAN NOT NULL CHECK (themeMateIn2 IN (0, 1)),
    themeMateIn3 BOOLEAN NOT NULL CHECK (themeMateIn3 IN (0, 1)),
    themeMateIn4 BOOLEAN NOT NULL CHECK (themeMateIn4 IN (0, 1)),
    themeMateIn5 BOOLEAN NOT NULL CHECK (themeMateIn5 IN (0, 1)),
    themeMiddlegame BOOLEAN NOT NULL CHECK (themeMiddlegame IN (0, 1)),
    themeOneMove BOOLEAN NOT NULL CHECK (themeOneMove IN (0, 1)),
    themeOpening BOOLEAN NOT NULL CHECK (themeOpening IN (0, 1)),
    themePawnEndgame BOOLEAN NOT NULL CHECK (themePawnEndgame IN (0, 1)),
    themePin BOOLEAN NOT NULL CHECK (themePin IN (0, 1)),
    themePromotion BOOLEAN NOT NULL CHECK (themePromotion IN (0, 1)),
    themeQueenEndgame BOOLEAN NOT NULL CHECK (themeQueenEndgame IN (0, 1)),
    themeQueenRookEndgame BOOLEAN NOT NULL CHECK (themeQueenRookEndgame IN (0, 1)),
    themeQueensideAttack BOOLEAN NOT NULL CHECK (themeQueensideAttack IN (0, 1)),
    themeQuietMove BOOLEAN NOT NULL CHECK (themeQuietMove IN (0, 1)),
    themeRookEndgame BOOLEAN NOT NULL CHECK (themeRookEndgame IN (0, 1)),
    themeSacrifice BOOLEAN NOT NULL CHECK (themeSacrifice IN (0, 1)),
    themeShort BOOLEAN NOT NULL CHECK (themeShort IN (0, 1)),
    themeSkewer BOOLEAN NOT NULL CHECK (themeSkewer IN (0, 1)),
    themeSmotheredMate BOOLEAN NOT NULL CHECK (themeSmotheredMate IN (0, 1)),
    themeSuperGM BOOLEAN NOT NULL CHECK (themeSuperGM IN (0, 1)),
    themeTrappedPiece BOOLEAN NOT NULL CHECK (themeTrappedPiece IN (0, 1)),
    themeUnderPromotion BOOLEAN NOT NULL CHECK (themeUnderPromotion IN (0, 1)),
    themeVeryLong BOOLEAN NOT NULL CHECK (themeVeryLong IN (0, 1)),
    themeXRayAttack BOOLEAN NOT NULL CHECK (themeXRayAttack IN (0, 1)),
    themeZugzwang BOOLEAN NOT NULL CHECK (themeZugzwang IN (0, 1))
);
