name: Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    pipes:
        uses: dragunovartem99/pipes/.github/workflows/deploy-vps.yaml@v1.2.0
        with:
            url: https://puzzfinder.dragunov.dev
        secrets: inherit
